FROM quay.io/keycloak/keycloak:25.0.4

COPY keycloak/custom-theme/org.keycloak.keycloak-themes-25.0.4.jar /opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-25.0.4.jar

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]